
-- ----------------------------
--  Records of stadium
-- ----------------------------

INSERT INTO wc_stadium(id, name, location) values

  (1, 'Luzhniki', 'Moscow'),
  (2, 'Zenit Arena', 'Petersburg'),
  (3, 'Fisht Olympic Stadium', 'Sochi'),
  (4, 'Volgograd Arena', 'Volgograd'),
  (5, 'Stadion Nizhny Novgorod', 'Nizhny Novgorod'),
  (6, 'Rostov Arena', 'Rostov-on-Don'),
  (7, 'Kazan Arena', 'Kazan'),
  (8, 'Samara Arena', 'Samara'),
  (9, 'Mordovia Arena', 'Saransk'),
  (10, 'Otkritie Arena', 'Moscow'),
  (11, 'Tsentralnyj Stadion', 'Yekaterinburg'),
  (12, 'Stadion Kaliningrad', 'Kaliningrad');





-- ----------------------------
--  Records of wc_country
-- ----------------------------

INSERT INTO wc_team(code, code_alt, name) values

  ('AD', 'AND', 'Andorra'),
  ('AE', 'ARE', 'United Arab Emirates'),
  ('AF', 'AFG', 'Afghanistan'),
  ('AG', 'ATG', 'Antigua and Barbuda'),
  ('AI', 'AIA', 'Anguilla'),
  ('AL', 'ALB', 'Albania'),
  ('AM', 'ARM', 'Armenia'),
  ('AO', 'AGO', 'Angola'),
  ('AR', 'ARG', 'Argentina'),
  ('AS', 'ASM', 'American Samoa'),
  ('AT', 'AUT', 'Austria'),
  ('AU', 'AUS', 'Australia'),
  ('AW', 'ABW', 'Aruba'),
  ('AZ', 'AZE', 'Azerbaijan'),
  ('BA', 'BIH', 'Bosnia and Herzegovina'),
  ('BB', 'BRB', 'Barbados'),
  ('BD', 'BGD', 'Bangladesh'),
  ('BE', 'BEL', 'Belgium'),
  ('BF', 'BFA', 'Burkina Faso'),
  ('BG', 'BGR', 'Bulgaria'),
  ('BH', 'BHR', 'Bahrain'),
  ('BI', 'BDI', 'Burundi'),
  ('BJ', 'BEN', 'Benin'),
  ('BM', 'BMU', 'Bermuda'),
  ('BN', 'BRN', 'Brunei'),
  ('BO', 'BOL', 'Bolivia'),
  ('BR', 'BRA', 'Brazil'),
  ('BS', 'BHS', 'Bahamas'),
  ('BT', 'BTN', 'Bhutan'),
  ('BW', 'BWA', 'Botswana'),
  ('BY', 'BLR', 'Belarus'),
  ('BZ', 'BLZ', 'Belize'),
  ('CA', 'CAN', 'Canada'),
  ('CC', 'CCK', 'Cocos Islands'),
  ('CD', 'COD', 'Democratic Republic of the Congo'),
  ('CF', 'CAF', 'Central African Republic'),
  ('CG', 'COG', 'Republic of the Congo'),
  ('CH', 'CHE', 'Switzerland'),
  ('CI', 'CIV', 'Cote d''Ivoire'),
  ('CK', 'COK', 'Cook Islands'),
  ('CL', 'CHL', 'Chile'),
  ('CM', 'CMR', 'Cameroon'),
  ('CN', 'CHN', 'China'),
  ('CO', 'COL', 'Colombia'),
  ('CR', 'CRI', 'Costa Rica'),
  ('CU', 'CUB', 'Cuba'),
  ('CV', 'CPV', 'Cape Verde'),
  ('CX', 'CXR', 'Christmas Island'),
  ('CY', 'CYP', 'Cyprus'),
  ('CZ', 'CZE', 'Czech Republic'),
  ('DE', 'DEU', 'Germany'),
  ('DJ', 'DJI', 'Djibouti'),
  ('DK', 'DNK', 'Denmark'),
  ('DM', 'DMA', 'Dominica'),
  ('DO', 'DOM', 'Dominican Republic'),
  ('DZ', 'DZA', 'Algeria'),
  ('EC', 'ECU', 'Ecuador'),
  ('EE', 'EST', 'Estonia'),
  ('EG', 'EGY', 'Egypt'),
  ('ER', 'ERI', 'Eritrea'),
  ('ES', 'ESP', 'Spain'),
  ('ET', 'ETH', 'Ethiopia'),
  ('FI', 'FIN', 'Finland'),
  ('FJ', 'FJI', 'Fiji'),
  ('FK', 'FLK', 'Falkland Islands'),
  ('FM', 'FM', 'Federated States of Micronesia'),
  ('FO', 'FRO', 'Faroe Islands'),
  ('FR', 'FRA', 'France'),
  ('GA', 'GAB', 'Gabon'),
  ('GB', 'GBR', 'United Kingdom'),
  ('GB-ENG', 'ENG', 'England'),
  ('GB-NIR', 'NIR', 'Northern Ireland'),
  ('GB-SCT', 'SCT', 'Scotland'),
  ('GB-WLS', 'WLS', 'Wales'),
  ('GD', 'GRD', 'Grenada'),
  ('GE', 'GEO', 'Georgia'),
  ('GF', 'GUF', 'French Guiana'),
  ('GH', 'GHA', 'Ghana'),
  ('GI', 'GIB', 'Gibraltar'),
  ('GL', 'GRL', 'Greenland'),
  ('GM', 'GMB', 'Gambia'),
  ('GN', 'GIN', 'Guinea'),
  ('GP', 'GLP', 'Guadeloupe'),
  ('GQ', 'GNQ', 'Equatorial Guinea'),
  ('GR', 'GRC', 'Greece'),
  ('GT', 'GTM', 'Guatemala'),
  ('GU', 'GUM', 'Guam'),
  ('GW', 'GNB', 'Guinea-Bissau'),
  ('GY', 'GUY', 'Guyana'),
  ('HK', 'HKG', 'Hong Kong'),
  ('HM', 'HMD', 'Heard and McDonald Islands'),
  ('HN', 'HND', 'Honduras'),
  ('HR', 'HRV', 'Croatia'),
  ('HT', 'HTI', 'Haiti'),
  ('HU', 'HUN', 'Hungary'),
  ('ID', 'IDN', 'Indonesia'),
  ('IE', 'IRL', 'Ireland'),
  ('IL', 'ISR', 'Israel'),
  ('IN', 'IND', 'India'),
  ('IO', 'IOT', 'British Indian Ocean Territory'),
  ('IQ', 'IRQ', 'Iraq'),
  ('IR', 'IRN', 'Iran'),
  ('IS', 'ISL', 'Iceland'),
  ('IT', 'ITA', 'Italy'),
  ('JM', 'JAM', 'Jamaica'),
  ('JO', 'JOR', 'Jordan'),
  ('JP', 'JPN', 'Japan'),
  ('KE', 'KEN', 'Kenya'),
  ('KG', 'KGZ', 'Kyrgyzstan'),
  ('KH', 'KHM', 'Cambodia'),
  ('KI', 'KIR', 'Kiribati'),
  ('KM', 'COM', 'Comoros'),
  ('KN', 'KP', 'St. Kitts and Nevis'),
  ('KP', 'PRK', 'North Korea'),
  ('KR', 'KOR', 'South Korea'),
  ('KW', 'KWT', 'Kuwait'),
  ('KY', 'CYM', 'Cayman Islands'),
  ('KZ', 'KAZ', 'Kazakhstan'),
  ('LA', 'LAO', 'Laos'),
  ('LB', 'LBN', 'Lebanon'),
  ('LC', 'LCA', 'St. Lucia'),
  ('LI', 'LIE', 'Liechtenstein'),
  ('LK', 'LKA', 'Sri Lanka'),
  ('LR', 'LBR', 'Liberia'),
  ('LS', 'LSO', 'Lesotho'),
  ('LT', 'LTU', 'Lithuania'),
  ('LU', 'LUX', 'Luxembourg'),
  ('LV', 'LVA', 'Latvia'),
  ('LY', 'LBY', 'Libya'),
  ('MA', 'MAR', 'Morocco'),
  ('MC', 'MCO', 'Monaco'),
  ('MD', 'MDA', 'Moldova'),
  ('ME', 'MNE', 'Montenegro'),
  ('MG', 'MDG', 'Madagascar'),
  ('MH', 'MHL', 'Marshall Islands'),
  ('MK', 'MK', 'F.Y.R.O. Macedonia'),
  ('ML', 'MLI', 'Mali'),
  ('MM', 'MMR', 'Myanmar'),
  ('MN', 'MNG', 'Mongolia'),
  ('MO', 'MAC', 'Macau'),
  ('MP', 'MNP', 'Northern Mariana Islands'),
  ('MQ', 'MTQ', 'Martinique'),
  ('MR', 'MRT', 'Mauritania'),
  ('MS', 'MSR', 'Montserrat'),
  ('MT', 'MLT', 'Malta'),
  ('MU', 'MUS', 'Mauritius'),
  ('MV', 'MDV', 'Maldives'),
  ('MW', 'MWI', 'Malawi'),
  ('MX', 'MX', 'Mexico'),
  ('MY', 'MYS', 'Malaysia'),
  ('MZ', 'MOZ', 'Mozambique'),
  ('NA', 'NAM', 'Namibia'),
  ('NC', 'NCL', 'New Caledonia'),
  ('NE', 'NER', 'Niger'),
  ('NF', 'NFK', 'Norfolk Island'),
  ('NG', 'NGA', 'Nigeria'),
  ('NI', 'NIC', 'Nicaragua'),
  ('NL', 'NLD', 'Netherlands'),
  ('NO', 'NOR', 'Norway'),
  ('NP', 'NPL', 'Nepal'),
  ('NR', 'NRU', 'Nauru'),
  ('NU', 'NIU', 'Niue'),
  ('NZ', 'NZL', 'New Zealand'),
  ('OM', 'OMN', 'Oman'),
  ('PA', 'PAN', 'Panama'),
  ('PE', 'PER', 'Peru'),
  ('PF', 'PYF', 'French Polynesia'),
  ('PG', 'PNG', 'Papua New Guinea'),
  ('PH', 'PHL', 'Philippines'),
  ('PK', 'PAK', 'Pakistan'),
  ('PL', 'POL', 'Poland'),
  ('PM', 'SPM', 'St. Pierre and Miquelon'),
  ('PN', 'PCN', 'Pitcairn Island'),
  ('PR', 'PRI', 'Puerto Rico'),
  ('PT', 'PRT', 'Portugal'),
  ('PW', 'PLW', 'Palau'),
  ('PY', 'PRY', 'Paraguay'),
  ('QA', 'QAT', 'Qatar'),
  ('RE', 'REU', 'Reunion'),
  ('RO', 'ROU', 'Romania'),
  ('RS', 'SRB', 'Serbia'),
  ('RU', 'RUS', 'Russia'),
  ('RW', 'RWA', 'Rwanda'),
  ('SA', 'SAU', 'Saudi Arabia'),
  ('SB', 'SLB', 'Solomon Islands'),
  ('SC', 'SYC', 'Seychelles'),
  ('SD', 'SDN', 'Sudan'),
  ('SE', 'SWE', 'Sweden'),
  ('SG', 'SGP', 'Singapore'),
  ('SH', 'SHN', 'St. Helena'),
  ('SI', 'SVN', 'Slovenia'),
  ('SJ', 'SJM', 'Svalbard'),
  ('SK', 'SVK', 'Slovakia'),
  ('SL', 'SLE', 'Sierra Leone'),
  ('SM', 'SMR', 'San Marino'),
  ('SN', 'SEN', 'Senegal'),
  ('SO', 'SOM', 'Federal Republic of Somalia'),
  ('SR', 'SUR', 'Suriname'),
  ('ST', 'STP', 'Sao Tome and Principe'),
  ('SV', 'SLV', 'El Salvador'),
  ('SY', 'SYR', 'Syria'),
  ('SZ', 'SWZ', 'Swaziland'),
  ('TC', 'TCA', 'Turks and Caicos'),
  ('TD', 'TCD', 'Chad'),
  ('TF', 'ATF', 'French Southern and Antarctic Territories'),
  ('TG', 'TGO', 'Togo'),
  ('TH', 'THA', 'Thailand'),
  ('TJ', 'TJK', 'Tajikistan'),
  ('TK', 'TKL', 'Tokelau'),
  ('TL', 'TLS', 'Timor Leste'),
  ('TM', 'TKM', 'Turkmenistan'),
  ('TN', 'TUN', 'Tunisia'),
  ('TO', 'TON', 'Tonga'),
  ('TR', 'TUR', 'Turkey'),
  ('TT', 'TTO', 'Trinidad and Tobago'),
  ('TV', 'TUV', 'Tuvalu'),
  ('TZ', 'TZA', 'Tanzania'),
  ('UA', 'UKR', 'Ukraine'),
  ('UG', 'UGA', 'Uganda'),
  ('UM', 'UMI', 'US Minor Outlying Islands'),
  ('US', 'USA', 'USA'),
  ('UY', 'URY', 'Uruguay'),
  ('UZ', 'UZB', 'Uzbekistan'),
  ('VA', 'VAT', 'Vatican City'),
  ('VC', 'VCT', 'St. Vincent and the Grenadines'),
  ('VE', 'VEN', 'Venezuela'),
  ('VG', 'VGB', 'British Virgin Islands'),
  ('VI', 'VIR', 'U.S. Virgin Islands'),
  ('VN', 'VNM', 'Vietnam'),
  ('VU', 'VUT', 'Vanuatu'),
  ('WF', 'WLF', 'Wallis and Futuna'),
  ('WS', 'WSM', 'Samoa'),
  ('YE', 'YEM', 'Yemen'),
  ('YT', 'MYT', 'Mayotte'),
  ('ZA', 'ZAF', 'South Africa'),
  ('ZM', 'ZWB', 'Zambia'),
  ('ZW', 'ZWE', 'Zimbabwe');




-- ----------------------------
--  Records of wc_fixture
-- ----------------------------

INSERT INTO wc_fixture(stage, datetime, local, visitor) values

  ('Group A', '2014-06-12 17:00:00', 'BR', 'HR'),
  ('Group A', '2014-06-13 13:00:00', 'MX', 'CM'),
  ('Group B', '2014-06-13 16:00:00', 'ES', 'NL'),
  ('Group B', '2014-06-13 18:00:00', 'CL', 'AU'),
  ('Group C', '2014-06-14 13:00:00', 'CO', 'GR'),
  ('Group D', '2014-06-14 16:00:00', 'UY', 'CR'),
  ('Group D', '2014-06-14 18:00:00', 'GB-ENG', 'IT'),
  ('Group C', '2014-06-14 22:00:00', 'CI', 'JP'),
  ('Group E', '2014-06-15 13:00:00', 'CH', 'EC'),
  ('Group E', '2014-06-15 16:00:00', 'FR', 'HN'),
  ('Group F', '2014-06-15 19:00:00', 'AR', 'BA'),
  ('Group G', '2014-06-16 13:00:00', 'DE', 'PT'),
  ('Group F', '2014-06-16 16:00:00', 'IR', 'NG'),
  ('Group G', '2014-06-16 19:00:00', 'GH', 'US'),
  ('Group H', '2014-06-17 13:00:00', 'BE', 'DZ'),
  ('Group A', '2014-06-17 16:00:00', 'BR', 'MX'),
  ('Group H', '2014-06-17 19:00:00', 'RU', 'KR'),
  ('Group B', '2014-06-18 13:00:00', 'AU', 'NL'),
  ('Group B', '2014-06-18 16:00:00', 'ES', 'CL'),
  ('Group A', '2014-06-18 19:00:00', 'CM', 'HR'),
  ('Group C', '2014-06-19 13:00:00', 'CO', 'CI'),
  ('Group D', '2014-06-19 16:00:00', 'UY', 'GB-ENG'),
  ('Group C', '2014-06-19 19:00:00', 'JP', 'GR'),
  ('Group D', '2014-06-20 13:00:00', 'IT', 'CR'),
  ('Group E', '2014-06-20 16:00:00', 'CH', 'FR'),
  ('Group E', '2014-06-20 19:00:00', 'HN', 'EC'),
  ('Group F', '2014-06-21 13:00:00', 'AR', 'IR'),
  ('Group G', '2014-06-21 16:00:00', 'DE', 'GH'),
  ('Group F', '2014-06-21 18:00:00', 'NG', 'BA'),
  ('Group H', '2014-06-22 13:00:00', 'BE', 'RU'),
  ('Group H', '2014-06-22 16:00:00', 'KR', 'DZ'),
  ('Group G', '2014-06-22 18:00:00', 'US', 'PT'),
  ('Group B', '2014-06-23 13:00:00', 'AU', 'ES'),
  ('Group B', '2014-06-23 13:00:00', 'NL', 'CL'),
  ('Group A', '2014-06-23 17:00:00', 'CM', 'BR'),
  ('Group A', '2014-06-23 17:00:00', 'HR', 'MX'),
  ('Group D', '2014-06-24 13:00:00', 'IT', 'UY'),
  ('Group D', '2014-06-24 13:00:00', 'CR', 'GB-ENG'),
  ('Group C', '2014-06-24 17:00:00', 'JP', 'CO'),
  ('Group C', '2014-06-24 17:00:00', 'GR', 'CI'),
  ('Group F', '2014-06-25 13:00:00', 'BA', 'IR'),
  ('Group F', '2014-06-25 13:00:00', 'NG', 'AR'),
  ('Group E', '2014-06-25 17:00:00', 'HN', 'CH'),
  ('Group E', '2014-06-25 17:00:00', 'EC', 'FR'),
  ('Group G', '2014-06-26 13:00:00', 'PT', 'GH'),
  ('Group G', '2014-06-26 13:00:00', 'US', 'DE'),
  ('Group H', '2014-06-26 17:00:00', 'KR', 'BE'),
  ('Group H', '2014-06-26 17:00:00', 'DZ', 'RU');





-- ----------------------------
--  Records of wc_standings
-- ----------------------------
INSERT INTO wc_standings(team, group_letter) SELECT distinct local, substr(stage, length(stage)-1, 2) as stage from wc_fixture order by stage;